include(GoogleTest)

function(panda_configure_test target)
    file(GLOB_RECURSE test_headers CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/*.hpp")
    panda_configure_target(${target} ${test_headers})
endfunction()

function(panda_add_test target level)
    cmake_parse_arguments(TEST "" "" "SOURCES;LIBRARIES;MOCKS" ${ARGN})
    if(TEST_UNPARSED_ARGUMENTS OR TEST_KEYWORDS_MISSING_VALUES OR NOT TEST_SOURCES)
        message(FATAL_ERROR "Invalid arguments for test ${target}")
    endif()
    add_executable(${target} ${TEST_SOURCES})
    set_target_properties(${target} PROPERTIES UNITY_BUILD OFF)
    target_link_libraries(${target} PRIVATE ${TEST_LIBRARIES} GTest::gmock_main)
    set(replacements "")
    foreach(mock IN LISTS TEST_MOCKS)
        if(NOT TARGET ${mock})
            message(FATAL_ERROR "Test ${target}: unknown mock target ${mock}")
        endif()
        get_target_property(dependency ${mock} PANDA_REPLACES)
        if(NOT dependency)
            message(FATAL_ERROR "Test ${target}: ${mock} was not declared with panda_add_mock")
        endif()
        if(dependency IN_LIST replacements)
            message(FATAL_ERROR "Test ${target}: multiple mocks replace ${dependency}")
        endif()
        list(APPEND replacements ${dependency})
        # Direct OBJECT dependencies supply definitions before static archives are searched.
        target_link_libraries(${target} PRIVATE ${mock})
    endforeach()
    panda_configure_test(${target})
    gtest_discover_tests(${target}
        TEST_PREFIX "${level}."
        PROPERTIES LABELS "${level}"
        DISCOVERY_TIMEOUT 15)
endfunction()

function(panda_add_mock target)
    cmake_parse_arguments(MOCK "" "REPLACES;API_LIBRARY" "SOURCES;LIBRARIES" ${ARGN})
    if(MOCK_UNPARSED_ARGUMENTS OR MOCK_KEYWORDS_MISSING_VALUES OR NOT MOCK_SOURCES OR NOT MOCK_REPLACES)
        message(FATAL_ERROR "Invalid arguments for mock ${target}")
    endif()
    if(NOT MOCK_API_LIBRARY)
        set(MOCK_API_LIBRARY "${MOCK_REPLACES}")
    endif()
    if(NOT TARGET "${MOCK_API_LIBRARY}")
        message(FATAL_ERROR "Mock ${target}: unknown API library ${MOCK_API_LIBRARY}")
    endif()
    get_target_property(api_type ${MOCK_API_LIBRARY} TYPE)
    if(api_type STREQUAL "SHARED_LIBRARY")
        message(FATAL_ERROR "Mock ${target}: shared libraries do not support archive-member replacement")
    endif()
    add_library(${target} OBJECT ${MOCK_SOURCES})
    set_target_properties(${target} PROPERTIES UNITY_BUILD OFF)
    set_property(TARGET ${target} PROPERTY PANDA_REPLACES ${MOCK_REPLACES})
    target_link_libraries(${target} PUBLIC ${MOCK_LIBRARIES} "$<COMPILE_ONLY:${MOCK_API_LIBRARY}>")
    panda_configure_test(${target})
endfunction()
