if(NOT CMAKE_HOST_WIN32 OR NOT CMAKE_GENERATOR MATCHES "^Ninja" OR CMAKE_CXX_COMPILER_LOADED)
    return()
endif()
if(CMAKE_CXX_COMPILER)
    get_filename_component(compiler_name "${CMAKE_CXX_COMPILER}" NAME)
else()
    get_filename_component(compiler_name "$ENV{CXX}" NAME)
endif()
if(compiler_name AND NOT compiler_name MATCHES "^cl(\\.exe)?$")
    return()
endif()

set(panda_msvc_environment "${CMAKE_BINARY_DIR}/panda-msvc-environment.cmake")
if(NOT EXISTS "${panda_msvc_environment}")
    if(NOT DEFINED ENV{VCToolsInstallDir})
        find_program(vswhere NAMES vswhere
            PATHS "$ENV{ProgramFiles\(x86\)}/Microsoft Visual Studio/Installer" REQUIRED)
        execute_process(COMMAND "${vswhere}" -latest -products *
            -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
            OUTPUT_VARIABLE installation OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
        if(NOT installation)
            message(FATAL_ERROR "MSVC requires Visual Studio or Build Tools with the C++ desktop workload")
        endif()
        file(WRITE "${CMAKE_BINARY_DIR}/panda-msvc-detect.cmd"
            "@echo off\ncall \"${installation}/Common7/Tools/VsDevCmd.bat\" -no_logo -arch=x64 -host_arch=x64 >nul\nif errorlevel 1 exit /b 1\nset\n")
        execute_process(COMMAND "$ENV{COMSPEC}" /d /c "${CMAKE_BINARY_DIR}/panda-msvc-detect.cmd"
            OUTPUT_VARIABLE environment COMMAND_ERROR_IS_FATAL ANY)
        foreach(name IN ITEMS INCLUDE LIB LIBPATH PATH VCToolsInstallDir)
            set(pattern "${name}")
            if(name STREQUAL "PATH")
                set(pattern "[Pp][Aa][Tt][Hh]")
            endif()
            string(REGEX MATCH "(^|\n)${pattern}=([^\r\n]*)" entry "${environment}")
            set(ENV{${name}} "${CMAKE_MATCH_2}")
        endforeach()
    endif()
    file(WRITE "${panda_msvc_environment}" "# Generated MSVC environment for this build directory.\n")
    foreach(name IN ITEMS INCLUDE LIB LIBPATH PATH VCToolsInstallDir)
        file(APPEND "${panda_msvc_environment}" "set(ENV{${name}} [==[$ENV{${name}}]==])\n")
    endforeach()
endif()
include("${panda_msvc_environment}")
set(PANDA_MSVC_LAUNCHER "${CMAKE_COMMAND};-DPANDA_MSVC_ENVIRONMENT=${panda_msvc_environment};-P;${CMAKE_CURRENT_LIST_DIR}/MsvcRun.cmake;--")
foreach(language IN ITEMS C CXX)
    set(CMAKE_${language}_COMPILER_LAUNCHER ${PANDA_MSVC_LAUNCHER} ${CMAKE_${language}_COMPILER_LAUNCHER})
    set(CMAKE_${language}_LINKER_LAUNCHER ${PANDA_MSVC_LAUNCHER} ${CMAKE_${language}_LINKER_LAUNCHER})
endforeach()
if(NOT CMAKE_CXX_COMPILER)
    set(CMAKE_CXX_COMPILER cl)
endif()
if(NOT CMAKE_C_COMPILER)
    set(CMAKE_C_COMPILER cl)
endif()
