if(PANDA_ENABLE_STACKTRACE)
    include(CheckCXXSourceCompiles)
    block(SCOPE_FOR VARIABLES)
        set(CMAKE_TRY_COMPILE_TARGET_TYPE EXECUTABLE)
        set(CMAKE_REQUIRED_LIBRARIES "")
        set(CMAKE_CXX_STANDARD 23)
        set(CMAKE_CXX_STANDARD_REQUIRED ON)
        set(probe "#include <stacktrace>\nint main() { return static_cast<int>(std::stacktrace::current().size()); }")
        check_cxx_source_compiles("${probe}" PANDA_STACKTRACE_DIRECT)
        if(NOT PANDA_STACKTRACE_DIRECT AND CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
            set(CMAKE_REQUIRED_LIBRARIES stdc++exp)
            check_cxx_source_compiles("${probe}" PANDA_STACKTRACE_WITH_LIBRARY)
        endif()
    endblock()
    if(NOT PANDA_STACKTRACE_DIRECT AND NOT PANDA_STACKTRACE_WITH_LIBRARY)
        message(FATAL_ERROR "std::stacktrace is unavailable. Install a supported standard library or set PANDA_ENABLE_STACKTRACE=OFF.")
    endif()
endif()
