name: Static Analysis
'on':
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
env:
  BUILD_TYPE: Release
jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.1.1
        with:
          version: latest
          cache: true
      - name: Install Clang-20
        run: |
          sudo apt update
          wget -qO- https://apt.llvm.org/llvm.sh | sudo bash -s -- 20 all
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-20 10
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-20 10
          sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-20 10
      - name: Install X11
        run: sudo apt install xorg-dev
      - name: Update CMake
        run: |
          sudo apt purge --auto-remove cmake
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
          sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ jammy main'
          sudo apt update
          sudo apt install cmake
      - name: Install tools
        run: |
          sudo apt install cppcheck
      - name: Configure CMake
        run: >-
          cmake -B ${{github.workspace}}/build
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DPD_ENABLE_CPPCHECK=ON
          -DPD_ENABLE_CLANG_TIDY=ON
          -DPD_WARNINGS_AS_ERRORS=ON
          -DPD_BUILD_APP=ON
          -DGLFW_BUILD_WAYLAND=OFF

      - name: Build
        run: 'cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}'