name: Static Analysis
'on':
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
env:
  BUILD_TYPE: Release
jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.1.1
        with:
          version: latest
          cache: true
      - name: Install Clang-16
        run: |
          sudo apt install libncurses5
          wget https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.0/clang+llvm-16.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz
          tar xf clang+llvm-16.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz
          cd clang+llvm-16.0.0-x86_64-linux-gnu-ubuntu-18.04
          sudo cp -R * /usr/local/
      - name: Install X11
        run: sudo apt install xorg-dev
      - name: Install tools
        run : |
          sudo apt install cppcheck
          sudo apt install clang-tidy
      - name: Configure CMake
        run: >-
          cmake -B ${{github.workspace}}/build
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DCMAKE_C_COMPILER=clang
          -DCMAKE_CXX_COMPILER=clang++
          -DPD_ENABLE_CPPCHECK=ON
          -DPD_ENABLE_CLANG_TIDY=ON
          -DPD_WARNINGS_AS_ERRORS=ON

      - name: Build
        run: 'cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}'